
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  host: db
  password: 12345678

test:
  <<: *default
  database: app_test
  host: <%= ENV['DB_HOST'] || 'db' %>
  password: <%= ENV['DB_PASSWORD'] || '12345678' %>

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] || 'postgres' %>
  username: <%= ENV['RDS_USERNAME'] || 'postgres' %>
  host: <%= ENV['RDS_HOSTNAME'] || 'db' %>
  password: <%= ENV['RDS_PASSWORD'] || '12345678' %>
  #url: <%= ENV['DATABASE_URL'] %>
  
